name: Validate YAML Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate YAML Syntax
        run: |
          find . -name "*.yml" -o -name "*.yaml" | xargs yamllint

      - name: Validate YAML Schema
        run: |
          for file in $(find . -name "*.yml" -o -name "*.yaml"); do
            ajv validate -s .github/schema/dog-schema.json -d "$file" || exit 1
          done
